spring:
  application:
    name: ad-trade-processor
  profiles:
    active: local
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:./data/db3;MODE=MYSQL
    username: sa
    password: password
  
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false
        web-allow-others: false
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: none
    
  
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
          
server:
  port: 8092
  servlet.context-path: /    

management:
  security:
    enabled: false

logging:
  pattern:
    console: Log - %msg%n
  level:
    root: error
    org.dev.ad: debug

trade-processor:
  stopLossPercent: 5
  breakEvenPercent: 3
  profitPercent1: 7
  profitPercent2: 10
  profitPercent3: 15

crawler:
  urls:
    downloads:
      - https://www.xvideos.com/video66698345/tall_beautiful_delhi_girl_brutally_fucked_by_her_brother