spring:
  application:
    name: ad-trade-processor
  profiles:
    active: local
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:./data/db3;MODE=MYSQL
    username: sa
    password: password
  
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false
        web-allow-others: false
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: none
    
  
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
          
server:
  port: 8092
  servlet.context-path: /    

management:
  security:
    enabled: false

logging:
  pattern:
    console: Log - %msg%n
  level:
    root: error
    org.dev.ad: debug

trade-processor:
  stopLossPercent: 5
  breakEvenPercent: 3
  profitPercent1: 7
  profitPercent2: 10
  profitPercent3: 15

crawler:
  urls:
    downloads:
      - https://www.xvideos.com/video66698345/tall_beautiful_delhi_girl_brutally_fucked_by_her_brother

instruments:
  names:
    APTECHT: ApTech
    ASTRAL: Astral Pipes
    AUROPHARMA: Aurobindo Pharmaceuticals
    AXISBANK: Axis Bank
    BAJFINANCE: Bajaj Finance
    BHARTIARTL: Bharti Airtel
    BIOCON: BioCon Pharmaceuticals
    CCL: CCL Products
    DEEPAKNTR: Deepak Nitrite
    ESCORTS: Escorts Kubota International
    LALPATHLAB: Dr. Lal PathLabs
    FEDERALBNK: Federal Bank
    GLENMARK: Glenmark Pharmaceuticals
    GOKEX: GokulDas Exports
    HDFCBANK: HDFC Bank
    ICICIBANK: ICICI Bank
    INFY: Infosys Ltd
    JUBLINGREA: Jubilant Ingrevia
    KOTAKBANK: Kotak Bank
    MPHASIS: Mphasis Ltd.
    NCC: NCC Ltd.
    RAJRATAN: RajRatan Global Wires
    SBIN: State Bank of India
    TATASTEEL: Tata Steel Ltd.
    YESBANK: Yes Bank
  ltp:
    APTECHT: 522.85
    ASTRAL: 1954.00
    AUROPHARMA: 669.75
    AXISBANK: 961.70
    BAJFINANCE: 7012.75
    BHARTIARTL: 799.35
    BIOCON: 245.05
    CCL: 632.20
    DEEPAKNTR: 2087.00
    ESCORTS: 2085.30
    LALPATHLAB: 2007.00
    FEDERALBNK: 126.35
    GLENMARK: 647.85
    GOKEX: 454.50
    HDFCBANK: 1608.35
    ICICIBANK: 938.95
    INFY: 1283.30
    JUBLINGREA: 427.50
    KOTAKBANK: 1888.00
    MPHASIS: 1868.05
    NCC: 124.80
    RAJRATAN: 836.80
    SBIN: 588.20
    TATASTEEL: 111.25
    YESBANK: 16.75