spring:
  application:
    name: ad-trade-processor
  profiles:
    active: local
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:./data/db3;MODE=MYSQL
    username: sa
    password: password
  
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: false
        web-allow-others: false
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: none
    
  
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
          
server:
  port: 8092
  servlet.context-path: /    

management:
  security:
    enabled: false

logging:
  pattern:
    console: Log - %msg%n
  level:
    root: error
    org.dev.ad: debug

trade-processor:
  stopLossPercent: 5
  breakEvenPercent: 3
  profitPercent1: 7
  profitPercent2: 10
  profitPercent3: 15

crawler:
  urls:
    downloads:
      - https://www.xvideos.com/video66698345/tall_beautiful_delhi_girl_brutally_fucked_by_her_brother

instruments:
  names:
    APTECHT: ApTech
    ASTRAL: Astral Pipes
    AUROPHARMA: Aurobindo Pharmaceuticals
    AXISBANK: Axis Bank
    BAJFINANCE: Bajaj Finance
    BHARTIARTL: Bharti Airtel
    BIOCON: BioCon Pharmaceuticals
    CCL: CCL Products
    DEEPAKNTR: Deepak Nitrite
    ESCORTS: Escorts Kubota International
    LALPATHLAB: Dr. Lal PathLabs
    FEDERALBNK: Federal Bank
    GLENMARK: Glenmark Pharmaceuticals
    GOKEX: GokulDas Exports
    HDFCBANK: HDFC Bank
    ICICIBANK: ICICI Bank
    INFY: Infosys Ltd
    JUBLINGREA: Jubilant Ingrevia
    KOTAKBANK: Kotak Bank
    MPHASIS: Mphasis Ltd.
    NCC: NCC Ltd.
    RAJRATAN: RajRatan Global Wires
    SBIN: State Bank of India
    TATASTEEL: Tata Steel Ltd.
    YESBANK: Yes Bank
  ltp:
    APTECHT: 416.50
    ASTRAL: 1443.00
    AUROPHARMA: 565.30
    AXISBANK: 864.00
    BAJFINANCE: 5901.50
    BHARTIARTL: 767.85
    BIOCON: 224.00
    CCL: 560.70
    DEEPAKNTR: 1871.90
    ESCORTS: 1958.40
    LALPATHLAB: 1905.00
    FEDERALBNK: 128.15
    GLENMARK: 490.10
    GOKEX: 356.90
    HDFCBANK: 1695.00
    ICICIBANK: 898.00
    INFY: 1383.40
    JUBLINGREA: 398.00
    KOTAKBANK: 1868.00
    MPHASIS: 1770.05
    NCC: 107.70
    RAJRATAN: 775.60
    SBIN: 533.40
    TATASTEEL: 107.60
    YESBANK: 15.25